name: mit_post
description: A Flutter based application to display notices, notify about events, and host articles published by The MIT Post. For the students, by the students.

publish_to: "none"

version: 3.1.0+87

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: 3.1.0+1
  http: ^0.12.2
  transparent_image: 1.0.0
  url_launcher: ^5.7.0
  twitter_api: ^0.1.2
  flutter_vibrate: ^1.0.0
  font_awesome_flutter: ^8.8.1
  shared_preferences: any
  firebase_messaging: ^7.0.0
  fluttertoast: ^7.1.1
  dynamic_scaler: 0.0.1
  flutter_statusbarcolor: 0.2.3
  html: ^0.14.0+3
  after_layout: ^1.0.7+2
  flutter_html: ^1.0.0
  cached_network_image: ^2.3.2+1
  flutter_staggered_animations: ^0.1.2
  share: ^0.6.5+2
  advance_pdf_viewer: ^1.2.0
  simple_animations: 1.3.12
  webview_flutter: ^0.3.21
  modal_progress_hud: ^0.1.3
  expandable: ^4.1.4
  confetti: 0.5.4+1
  flutter_markdown: 0.5.2
  quick_actions: 0.4.0+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  # Official font of The MIT Post
  fonts:
    #<YOUR-FONTS-HERE>
